image: 
  file: .gitpod.dockerfile

tasks:
  - name: Init project
    init: |
      sudo locale-gen en_US.UTF-8
      sudo update-locale LANG=en_US.UTF-8
      python3 -m venv .venv
      . .venv/bin/activate
      # upgrade some dependencies
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      echo "gitpod workspace initiated"
  - name: Command
    command: |
      . .venv/bin/activate
      echo "Setting locale to UTF-8"
      export LANG=en_US.UTF-8
      export LC_ALL=en_US.UTF-8
      echo "Welcome to your gitpod workspace with venv!"

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
